### ISSUE TITLE
Forms in DEC should have the same width

### ISSUE THREAD

**Issue by AnastasiiaLypovenko** [jauntin/pdf-platform-sdk#12]
## Question
Should we merge pr https://github.com/jauntin/platform/pull/62?

## Additional information 
Dasha fixed an issue in this pr https://github.com/jauntin/platform/pull/62. Original ticket is https://github.com/jauntin/gatherguard/issues/209, firstly, we decided to add margin to coi document, but then removed coi from sample.
![Image](https://github.com/jauntin/pdf-platform-sdk/assets/129950478/b9bb68c0-0004-4c71-b21f-e4874c73a0bb)

**Comment by raines88** [comment]
@AnastasiiaLypovenko Closing this for now since it's not needed.
